#!/bin/bash

# Путь к файлу Python скрипта
python_script="awards_v4.1.py"

# Путь к каталогу, в котором находится Python скрипт
directory="/home/alex320388/awards/"


# Проверяем наличие файла
if [ -f "$directory/$python_script" ]; then
    #echo "Файл $python_script существует в директории $directory."
    
    # Переходим в каталог
    cd "$directory"
    source ~/venv/bin/activate

    # Запускаем скрипт на Python
    python3 "$python_script"
else
    echo "Файл $python_script не найден в директории $directory."
    #notify-send "Файл $python_script не найден в директории $directory."
fi
