name: Build Windows Exe

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install SQLCipher
      run: |
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install sqlcipher:x64-windows

    - name: Set SQLCipher env
      run: |
        echo "INCLUDE=%CD%\vcpkg\installed\x64-windows\include" >> $env:GITHUB_ENV
        echo "LIB=%CD%\vcpkg\installed\x64-windows\lib" >> $env:GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install wxPython Pillow bs4 openpyxl requests pyinstaller
        pip install sqlcipher3

    - name: Build exe
      run: pyinstaller --clean main.spec

    - uses: actions/upload-artifact@v4
      with:
        name: awardswx-windows-exe
        path: dist/
